# Generated by Django 5.2.17 on 2026-09-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='titulo')),
                ('autor', models.CharField(max_length=100, verbose_name='autor')),
                ('ano', models.PositiveIntegerField(verbose_name='ano')),
                ('disponivel', models.BooleanField(default=True, verbose_name='disponivel')),
                ('tipo_acervo', models.CharField(choices=[('digital', 'Digital'), ('fisico', 'Fisico')], default='fisico', max_length=10, verbose_name='tipo de acervo')),
                ('categoria', models.CharField(choices=[('000', '000 - Generalidades e Informacao'), ('100', '100 - Filosofia e Psicologia'), ('200', '200 - Religiao e Teologia'), ('300', '300 - Ciencias Sociais e Direito'), ('400', '400 - Linguistica e Idiomas'), ('500', '500 - Ciencias Puras'), ('600', '600 - Ciencias Aplicadas'), ('700', '700 - Artes e Recreacao'), ('800', '800 - Literatura'), ('900', '900 - Historia e Geografia')], default='000', max_length=3, verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'livro',
                'verbose_name_plural': 'livros',
                'ordering': ['titulo'],
            },
        ),
    ]
