# Generated by Django 5.2.17 on 2026-09-23 22:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def migrar_autores(apps, schema_editor):
    Autor = apps.get_model('acervo', 'Autor')
    Livro = apps.get_model('acervo', 'Livro')

    for livro in Livro.objects.all():
        nome = livro.autor_legado.strip() or 'Autor desconhecido'
        autor, _ = Autor.objects.get_or_create(nome=nome)
        livro.autor = autor
        livro.save(update_fields=['autor'])


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('nacionalidade', models.CharField(blank=True, max_length=80, verbose_name='nacionalidade')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
            ],
            options={
                'verbose_name': 'autor',
                'verbose_name_plural': 'autores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name='telefone')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, verbose_name='cadastrado em')),
            ],
            options={
                'verbose_name': 'membro',
                'verbose_name_plural': 'membros',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='livro',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ISBN'),
        ),
        migrations.RenameField(
            model_name='livro',
            old_name='autor',
            new_name='autor_legado',
        ),
        migrations.AlterField(
            model_name='livro',
            name='categoria',
            field=models.CharField(choices=[('000', '000 - Generalidades e Informacao'), ('100', '100 - Filosofia e Psicologia'), ('200', '200 - Religiao e Teologia'), ('300', '300 - Ciencias Sociais e Direito'), ('400', '400 - Linguistica e Idiomas'), ('500', '500 - Ciencias Puras (Exatas e Naturais)'), ('600', '600 - Ciencias Aplicadas (Tecnologia)'), ('700', '700 - Artes e Recreacao'), ('800', '800 - Literatura'), ('900', '900 - Historia e Geografia')], default='000', max_length=3, verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='disponivel',
            field=models.BooleanField(default=True, verbose_name='ativo no acervo'),
        ),
        migrations.AddField(
            model_name='livro',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='acervo.autor', verbose_name='autor'),
        ),
        migrations.RunPython(migrar_autores, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='livro',
            name='autor_legado',
        ),
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='acervo.autor', verbose_name='autor'),
        ),
        migrations.CreateModel(
            name='Exemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True, verbose_name='codigo patrimonial')),
                ('localizacao', models.CharField(blank=True, max_length=100, verbose_name='localizacao')),
                ('status', models.CharField(choices=[('disponivel', 'Disponivel'), ('emprestado', 'Emprestado'), ('manutencao', 'Em manutencao')], default='disponivel', max_length=12, verbose_name='status')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemplares', to='acervo.livro', verbose_name='livro')),
            ],
            options={
                'verbose_name': 'exemplar',
                'verbose_name_plural': 'exemplares',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emprestado_em', models.DateField(default=django.utils.timezone.localdate, verbose_name='emprestado em')),
                ('vencimento', models.DateField(verbose_name='vencimento')),
                ('devolvido_em', models.DateField(blank=True, null=True, verbose_name='devolvido em')),
                ('multa', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='multa')),
                ('exemplar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='acervo.exemplar', verbose_name='exemplar')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='acervo.membro', verbose_name='membro')),
            ],
            options={
                'verbose_name': 'emprestimo',
                'verbose_name_plural': 'emprestimos',
                'ordering': ['-emprestado_em', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('devolvido_em__isnull', True)), fields=('exemplar',), name='exemplar_com_um_emprestimo_ativo')],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitada_em', models.DateTimeField(auto_now_add=True, verbose_name='solicitada em')),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('atendida', 'Atendida'), ('cancelada', 'Cancelada')], default='aguardando', max_length=10, verbose_name='status')),
                ('finalizada_em', models.DateTimeField(blank=True, null=True, verbose_name='finalizada em')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='acervo.livro', verbose_name='livro')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='acervo.membro', verbose_name='membro')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'ordering': ['solicitada_em', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'aguardando')), fields=('livro', 'membro'), name='uma_reserva_ativa_por_membro_e_livro')],
            },
        ),
    ]
